name: beta_poison
channels:
  - pytorch
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - pkg-config
  - freetype
  - libpng
  - openblas  # MKL yerine OpenBLAS kullanılıyor
  - nomkl  # MKL'yi devre dışı bırakmak için
  - ca-certificates
  - certifi
  - cloudpickle
  - cytoolz
  - dask-core
  - dbus
  - decorator
  - dill
  - expat
  - fontconfig
  - freetype
  - glib
  - gpy
  - gpyopt
  - gst-plugins-base
  - gstreamer
  - icu
  - imageio
  - joblib
  - jpeg
  - kiwisolver
  - lcms2
  - libedit
  - libffi
  - libxml2
  - lz4-c
  - multiprocess
  - ncurses
  - networkx
  - ninja
  - numpy-base
  - olefile
  - openssl
  - pandas
  - paramz
  - pcre
  - plotly
  - pyparsing
  - pyqt
  - python-dateutil
  - pytz
  - pywavelets
  - pyyaml
  - qt
  - readline
  - retrying
  - scikit-image
  - scikit-learn
  - seaborn
  - setuptools
  - sip
  - six
  - sqlite
  - threadpoolctl
  - tk
  - toolz
  - torchvision
  - tornado
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - aiohttp
    - aiohttp-cors
    - aioredis
    - async-timeout
    - attrs
    - beautifulsoup4
    - blessings
    - cachetools
    - chardet
    - click
    - colorama
    - colorful
    - eagerpy
    - filelock
    - foolbox
    - gitdb
    - gitpython
    - google
    - google-api-core
    - google-auth
    - googleapis-common-protos
    - gpustat
    - grpcio
    - hiredis
    - idna
    - import-ipynb
    - importlib-metadata
    - jsonschema
    - llvmlite
    - matplotlib
    - mpu
    - msgpack
    - multidict
    - numba
    - nvidia-ml-py3
    - opencensus
    - opencensus-context
    - pillow
    - prometheus-client
    - protobuf
    - psutil
    - py-spy
    - pyasn1
    - pyasn1-modules
    - pyrsistent
    - ray
    - redis
    - requests
    - rsa
    - scipy
    - secml
    - scikit-learn
    - smmap
    - soupsieve
    - typing-extensions
    - urllib3
    - yarl
    - zipp